%% Import data from spreadsheet
% Script for importing data from the following spreadsheet:
%
%    Workbook: /Users/jonesyli/Desktop/RESET COMP.xlsx
%    Worksheet: Use this as Ind. Data
%
% To extend the code for use with different selected data or a different
% spreadsheet, generate a function instead of a script.

% Auto-generated by MATLAB on 2018/11/01 00:25:22

%% Import the data
[~, ~, raw] = xlsread('/Users/jonesyli/Desktop/RESET COMP.xlsx','Use this as Ind. Data');
raw = raw(:,[3,6:end]);
raw(cellfun(@(x) ~isempty(x) && isnumeric(x) && isnan(x),raw)) = {''};

%% Exclude rows with non-numeric cells
I = ~all(cellfun(@(x) (isnumeric(x) || islogical(x)) && ~isnan(x),raw),2); % Find rows with non-numeric cells
raw(I,:) = [];

%% Create output variable
data = reshape([raw{:}],size(raw));


%% Allocate imported array to column variable names
Salary = data(:,1);
MINUTES = data(:,2);
FGM = data(:,3);
FGA = data(:,4);
TPM = data(:,5);
TPA = data(:,6);
FTM = data(:,7);
FTA = data(:,8);
TOV = data(:,9);
PF = data(:,10);
ORB = data(:,11);
DRB = data(:,12);
TRB = data(:,13);
AST = data(:,14);
STL = data(:,15);
BLK = data(:,16);
PTS = data(:,17);
TS = data(:,18);
PACE = data(:,19);

%% Clear temporary variables
clearvars data raw I;

%% Import data from spreadsheet
% Script for importing data from the following spreadsheet:
%
%    Workbook: /Users/jonesyli/Desktop/RESET COMP.xlsx
%    Worksheet: Use this as Championshp Data
%
% To extend the code for use with different selected data or a different
% spreadsheet, generate a function instead of a script.

% Auto-generated by MATLAB on 2018/11/01 00:35:16

%% Import the data
[~, ~, raw] = xlsread('/Users/jonesyli/Desktop/RESET COMP.xlsx','Use this as Championshp Data');
raw = raw(12,2:19);

%% Create output variable
data = reshape([raw{:}],size(raw));

%% Allocate imported array to column variable names
MP = data(:,1);
TFGM = data(:,2);
TFGA = data(:,3);
TTPM = data(:,4);
TTPA = data(:,5);
TFTM = data(:,6);
TFTA = data(:,7);
TTOV = data(:,8);
TPF = data(:,9);
TORB = data(:,10);
TDRB = data(:,11);
TTRB = data(:,12);
TAST = data(:,13);
TSTL = data(:,14);
TBLK = data(:,15);
TPTS = data(:,16);
TPACE = data(:,17);
TTS = data(:,18);

%% Clear temporary variables
clearvars data raw;


PLAYERS = [ones(1:282)]
f = [Salary']/1000000;
A = -[ PLAYERS PLAYERS -MINUTES PTS AST TRB STL BLK FGA FGM FTA FTM TPA TPM PACE/13 -PF ORB DRB -TOV]'
b = -[ 13; -15; -MP; TPTS; TAST; TTRB; TSTL; TBLK; TFGA; TFGM; TFTA; TFTM; T3PA; T3PM; TPACE; -TPF; TORB; TDRB; -TTOV]
Aeq = []
beq = []
lb = [zeros(1,282)]
ub = [ones(1,282)]
intcon = [1:282]


[X,Z] = intlinprog(f,intcon,A,b,Aeq,beq,lb,ub)

Y = nnz(X)

