%% Import data from spreadsheet
% Script for importing data from the following spreadsheet:
%
%    Workbook: /Users/jonesyli/Desktop/RESET COMP.xlsx
%    Worksheet: Use this as Ind. Data
%
% To extend the code for use with different selected data or a different
% spreadsheet, generate a function instead of a script.

% Auto-generated by MATLAB on 2018/11/20 02:36:23

%% Import the data
[~, ~, raw] = xlsread('/Users/jonesyli/Desktop/RESET COMP.xlsx','Use this as Ind. Data');
raw = raw(:,6:end);
raw(cellfun(@(x) ~isempty(x) && isnumeric(x) && isnan(x),raw)) = {''};

%% Exclude rows with non-numeric cells
I = ~all(cellfun(@(x) (isnumeric(x) || islogical(x)) && ~isnan(x),raw),2); % Find rows with non-numeric cells
raw(I,:) = [];

%% Create output variable
data = reshape([raw{:}],size(raw));

%% Allocate imported array to column variable names
MINUTES = data(:,1);
FGM = data(:,2);
FGA = data(:,3);
TPM = data(:,4);
TPA = data(:,5);
FTM = data(:,6);
FTA = data(:,7);
TOV = data(:,8);
PF = data(:,9);
ORB = data(:,10);
DRB = data(:,11);
TRB = data(:,12);
AST = data(:,13);
STL = data(:,14);
BLK = data(:,15);
PTS = data(:,16);
TS = data(:,17);
PACE = data(:,18);

%% Clear temporary variables
clearvars data raw I;


alpha = 0.1
PLAYERS = [ones(282,1); 0]
Value = [-1*alpha]
Index = [283]
SSalary = [Salary]'/1000000
SSSalary = [SSalary]
%; nan(size(SSalary))]
SSSalary(1, Index) = Value;
Result = SSSalary(isfinite(SSSalary)).'


A = -[ PLAYERS -PLAYERS -MINUTES PTS AST TRB STL BLK FGA FGM FTA FTM TPA TPM ORB DRB [zeros(282,1); 1] TPM ]'
b = -[13; -15; -311.68; 132.79; 30.2; 56.51; 10.14; 7.59; 105.84; 50.19; 28.13; 21.49; 29.51; 11.14; 13.3; 43.31; 11.14; 0]
Aeq = [];
beq = [];
lb = [zeros(1,283)];
ub = [ones(1,282) inf];
intcon = [1:282]

A(17,283) = -1;
A(18,283) = 1;

f = Result';

options = optimoptions('intlinprog', 'Display', 'iter');
[X,fval,exitflag, output] = intlinprog(f,intcon,A,b,Aeq,beq,lb,ub,options)

k = find(X ==1)
Y = (fval + alpha* 11.14)
